from enum import Enum


class DownloadStatus(Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"


class SeedrStatus(Enum):
    IDLE = "IDLE"
    PROCESSING = "PROCESSING"
    DOWNLOADING = "DOWNLOADING"
    DOWNLOAD_CHECKING = "DOWNLOAD_CHECKING"
    UPLOADING = "UPLOADING"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"