# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
    push:
        branches: ["main"]
    workflow_dispatch:
        inputs:
            pods:
                type: number
                description: Number of pods to use
                required: true
                default: 1

permissions:
    contents: read

jobs:
    pre-build:
        runs-on: ubuntu-latest
        outputs:
            pods: ${{ steps.set-pods.outputs.pods }}
        steps:
            - name: Set pods count
              id: set-pods
              run: |
                  num=${{ inputs.pods || 1 }}

                  if ! [[ $num =~ ^[0-9]+$ ]]; then
                      echo "Error: Please enter a valid positive integer."
                      exit 1
                  fi

                  output="["
                  for ((i=1; i<=num; i++)); do
                      output+=" $i"
                      if ((i < num)); then
                          output+=','
                      fi
                  done
                  output+=" ]"

                  echo pods=$output >> $GITHUB_OUTPUT

    build:
        needs: pre-build
        strategy:
            fail-fast: false
            matrix:
                pods: ${{ fromJson(needs.pre-build.outputs.pods) }}

        runs-on: ubuntu-latest

        env:
            ENV: ${{ secrets.ENV }}

        steps:
            - uses: actions/checkout@v4
              with:
                  repository: iossos-proton/rssbox-seedr

            - name: Set up Python 3
              uses: actions/setup-python@v5
              with:
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Configure for testing
              run: |
                  echo "$ENV" > .env

            - name: Test with python
              run: |
                  python3 -m rssbox
